### ISSUE TITLE
Solargraph crashes on Ruby file open

### ISSUE THREAD

**Issue by prdanelli** [williamboman/mason-lspconfig.nvim#14]
### Problem description

Opening a Ruby file causes an error message: 

> 2022-07-28T21:17:01  WARN Client 3 quit with exit code 1 and signal 0

### Why do you think this is an issue with mason-lspconfig.nvim?

LSP functionality works correctly using Nvim Lsp Install 

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-nightly-221-g1a07044c1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin M1MacBookPro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

Solargraph 0.45.0

### Steps to reproduce

Install via Mason
Open Ruby file

### Actual behavior

No LSP for Ruby files

### Expected behavior

LSP for Ruby files

### LspInfo

```Text
Language client log: /Users/paul/.local/state/nvim/lsp.log
 Detected filetype:   ruby
 
 0 client(s) attached to this buffer: 
 
 1 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 8360, bufnr: [6])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/paul/Personal/Repos/dotfiles
 	cmd:             lua-language-server
 
 Other clients that match the filetype: ruby
 
 Config: solargraph
 	filetypes:         ruby
 	root directory:    /Users/paul/Dev/api
 	cmd:               solargraph stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: tsserver, sqlls, lemminx, html, dockerls, cssls, bashls, jsonls, solargraph, sumneko_lua, yamlls
```

### LspLog

```Text
[START][2022-07-28 21:19:24] LSP logging initiated
[ERROR][2022-07-28 21:19:24] .../vim/lsp/rpc.lua:439	"rpc"	"solargraph"	"stderr"	"/Users/paul/.asdf/installs/ruby/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)\n\tfrom /Users/paul/.asdf/installs/ruby/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'\n\tfrom /Users/paul/.local/share/nvim/mason/bin/solargraph:25:in `<main>'\n"
[ERROR][2022-07-28 21:19:24] .../vim/lsp/rpc.lua:439	"rpc"	"solargraph"	"stderr"	"/Users/paul/.asdf/installs/ruby/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException"
[ERROR][2022-07-28 21:19:24] .../vim/lsp/rpc.lua:439	"rpc"	"solargraph"	"stderr"	")\n\tfrom /Users/paul/.asdf/installs/ruby/3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'\n\tfrom /Users/paul/.local/share/nvim/mason/bin/solargraph:25:in `<main>'\n"
```
```


### Healthcheck

```Text
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - OK: **luarocks**: `/opt/homebrew/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]`
  - OK: **RubyGem**: `3.3.10`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `6.14.15`
  - OK: **node**: `v14.18.3`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.1.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 6. Remaining: 54. Limit: 60. Reset: Thu 28 Jul 21:26:47 2022.
```
```


### Screenshots or recordings

_No response_

**Comment by williamboman** [comment]
Hey! This is due to https://github.com/williamboman/mason.nvim/issues/152. Unfortunately all gem-based packages (three of them in total) are not functional yet with Mason. I've been reading up and experimenting with different solutions, will hopefully land something today

**Comment by prdanelli** [comment]
Thank you for confirming. I look forward to any updates you're able to
make.

Thank you for the time you've put into this project.

**Comment by williamboman** [comment]
Hey this should be fixed now. Let's reopen if you're still experiencing issues (you'll need to reinstall affected packages)

**Comment by prdanelli** [comment]
> Hey this should be fixed now. Let's reopen if you're still experiencing issues (you'll need to reinstall affected packages)

Unfortunately, using the same config as LspInstaller (but following the instructions to switch to Mason LSP Installer), i'm getting the same issue with the Solargraph LSP. Lua's LSP works perfectly.

**Comment by williamboman** [comment]
> Unfortunately, using the same config as LspInstaller (but following the instructions to switch to Mason LSP Installer), i'm getting the same issue with the Solargraph LSP. Lua's LSP works perfectly.

Hmm.. Are you getting any errors? Can you run `$ solargraph stdio` in the terminal (`:term`)?

**Comment by prdanelli** [comment]
I am able to run `solargraph stdio` (once I manually install the gem). 

When I open a Ruby file in Nvim with Mason installed, I get the following: 

```
Error executing luv callback:
vim/shared.lua:0: attempt to index a nil value
stack traceback:
        vim/shared.lua: in function 'tbl_get'
        ...neovim/HEAD-3ee6c05_1/share/nvim/runtime/lua/vim/lsp.lua:403: in function 'get_group'
        ...neovim/HEAD-3ee6c05_1/share/nvim/runtime/lua/vim/lsp.lua:525: in function 'reset'
        ...neovim/HEAD-3ee6c05_1/share/nvim/runtime/lua/vim/lsp.lua:1151: in function 'on_exit'
        ...im/HEAD-3ee6c05_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:329: in function <...im/HEAD-3ee6c05_1/s
hare/nvim/runtime/lua/vim/lsp/rpc.lua:321>
        [C]: in function '__newindex'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:8: in function 'setf'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:14: in function 'set_filetype'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:65: in function 'try_lookup'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:158: in function 'resolve'
        [string ":lua"]:1: in main chunk
        [C]: at 0x010239abb0
        [C]: in function 'pcall'
        ...site/pack/packer/start/auto-session/lua/auto-session.lua:480: in function 'restore'
        ...site/pack/packer/start/auto-session/lua/auto-session.lua:519: in function <...site/pack/packer/st
art/auto-session/lua/auto-session.lua:471>
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:110: in function 'apply_cause_side_effct
s'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:158: in function <...m/site/pack/packer/
start/packer.nvim/lua/packer/load.lua:118>
        [C]: in function 'pcall'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:162: in function <...m/site/pack/packer/
start/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

**Comment by mario-amazing** [comment]
Have the same trouble with solargraph. 
From `:term` it looks fine: 
```
solargraph stdio          ✔  3.0.2 
Solargraph is listening on stdio PID=3661
```

But in LspLog:
```
[ERROR][2022-08-12 03:06:54] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=3753\n"
[ERROR][2022-08-12 03:06:55] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/bundler-2.3.20/lib/bundler/definition.rb:514:in `materialize': Could not find racc-1.6.0 in locally installed gems (Bundler::GemNotFound)\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/bundler-2.3.20/lib/bundler/definition.rb:257:in `specs_for'\n\tfrom -e:1:in `block in <main>'\n\tfrom -e:1:in `chdir'\n\tfrom -e:1:in `<main>'\n\n"
[ERROR][2022-08-12 03:06:55] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] Failed to load gems from bundle at /Users/mario/work/this_moment\n"
[ERROR][2022-08-12 03:06:57] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"#<Thread:0x0000000112edddf8 /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2022-08-12 03:06:57] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"<internal:/Users/mario/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rubocop-rails (LoadError)\n"
[ERROR][2022-08-12 03:06:57] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"\tfrom <internal:/Users/mario/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/feature_loader.rb:35:in `load'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/feature_loader.rb:21:in `load'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader_resolver.rb:13:in `each'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'\n\tfrom <internal:kernel>:90:in `tap'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader.rb:46:in `load_file'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_loader.rb:104:in `configuration_from_file'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_store.rb:68:in `for_dir'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/config_store.rb:58:in `for'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:190:in `block in process_explicit_path'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:189:in `reject'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:189:in `process_explicit_path'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:40:in `block in find'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:36:in `each'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/target_finder.rb:36:in `find'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/runner.rb:81:in `find_target_files'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/rubocop-1.34.1/lib/rubocop/runner.rb:42:in `run'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/diagnostics/rubocop.rb:29:in `block in diagnose'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/diagnostics/rubocop_helpers.rb:57:in `redirect_stdout'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/diagnostics/rubocop.rb:29:in `diagnose'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/library.rb:363:in `block in diagnose'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/library.rb:362:in `each_pair'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/library.rb:362:in `diagnose'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/language_server/host.rb:211:in `diagnose'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/language_server/host/diagnoser.rb:66:in `tick'\n\tfrom /Users/mario/.local/share/nvim/mason/packages/solargraph/gems/solargraph-0.45.0/lib/solargraph/language_server/host/diagnoser.rb:47:in `block in start'\n"
```

**Comment by Slotos** [comment]
@mario-amazing your issue is due to missing gems in gem path that mason sets up. See https://github.com/williamboman/nvim-lsp-installer/issues/187 for reference.

You’ll need to periodically run `bundle install` with `GEM_PATH` and `GEM_HOME` set to mason’s solargraph install path.

**Comment by Slotos** [comment]
I did manage to ~gut~ modify gem manager to work with system with there two diffs

mason.nvim:
```diff
diff --git a/lua/mason-core/managers/system-gem/init.lua b/lua/mason-core/managers/system-gem/init.lua
new file mode 100644
index 0000000..72b4529
--- /dev/null
+++ b/lua/mason-core/managers/system-gem/init.lua
@@ -0,0 +1,131 @@
+local _ = require "mason-core.functional"
+local Result = require "mason-core.result"
+local spawn = require "mason-core.spawn"
+local Optional = require "mason-core.optional"
+local installer = require "mason-core.installer"
+
+local M = {}
+
+---@param packages string[]
+local function with_receipt(packages)
+    return function()
+        local ctx = installer.context()
+        ctx.receipt:with_primary_source(ctx.receipt.gem(packages[1]))
+        for i = 2, #packages do
+            ctx.receipt:with_secondary_source(ctx.receipt.gem(packages[i]))
+        end
+    end
+end
+
+---@async
+---@param packages { [number]: string, bin: string[]? } The Gem packages to install. The first item in this list will be the recipient of the requested version, if set.
+function M.packages(packages)
+    return function()
+        return M.install(packages).with_receipt()
+    end
+end
+
+---@async
+---@param packages { [number]: string, bin: string[]? } The Gem packages to install. The first item in this list will be the recipient of the requested version, if set.
+function M.install(packages)
+    local ctx = installer.context()
+    local pkgs = _.list_copy(packages or {})
+
+    ctx.requested_version:if_present(function(version)
+        pkgs[1] = ("%s:%s"):format(pkgs[1], version)
+    end)
+
+    ctx.spawn.gem {
+        "install",
+        pkgs,
+    }
+
+    return {
+        with_receipt = with_receipt(packages),
+    }
+end
+
+---@alias GemOutdatedPackage {name:string, current_version: string, latest_version: string}
+
+---Parses a string input like "package (0.1.0 < 0.2.0)" into its components
+---@param outdated_gem string
+---@return GemOutdatedPackage
+function M.parse_outdated_gem(outdated_gem)
+    local package_name, version_expression = outdated_gem:match "^(.+) %((.+)%)"
+    if not package_name or not version_expression then
+        -- unparsable
+        return nil
+    end
+    local current_version, latest_version = unpack(vim.split(version_expression, "<"))
+
+    ---@type GemOutdatedPackage
+    local outdated_package = {
+        name = vim.trim(package_name),
+        current_version = vim.trim(current_version),
+        latest_version = vim.trim(latest_version),
+    }
+    return outdated_package
+end
+
+---Parses the stdout of the `gem list` command into a table<package_name, version>
+---@param output string
+function M.parse_gem_list_output(output)
+    ---@type table<string, string>
+    local gem_versions = {}
+    for _, line in ipairs(vim.split(output, "\n")) do
+        local gem_package, version = line:match "^(%S+) %((%S+)%)$"
+        if gem_package and version then
+            gem_versions[gem_package] = version
+        end
+    end
+    return gem_versions
+end
+
+local function not_empty(s)
+    return s ~= nil and s ~= ""
+end
+
+---@async
+---@param receipt InstallReceipt<InstallReceiptPackageSource>
+---@param _install_dir string
+---@diagnostic disable-next-line: unused-local
+function M.check_outdated_primary_package(receipt, _install_dir)
+    if receipt.primary_source.type ~= "gem" then
+        return Result.failure "Receipt does not have a primary source of type gem"
+    end
+    return spawn.gem({ "outdated" }):map_catching(function(result)
+        ---@type string[]
+        local lines = vim.split(result.stdout, "\n")
+        local outdated_gems = vim.tbl_map(M.parse_outdated_gem, vim.tbl_filter(not_empty, lines))
+
+        local outdated_gem = _.find_first(function(gem)
+            return gem.name == receipt.primary_source.package and gem.current_version ~= gem.latest_version
+        end, outdated_gems)
+
+        return Optional.of_nilable(outdated_gem)
+            :map(function(gem)
+                return {
+                    name = receipt.primary_source.package,
+                    current_version = assert(gem.current_version, "current_version missing in gem"),
+                    latest_version = assert(gem.latest_version, "latest_version missing in gem"),
+                }
+            end)
+            :or_else_throw "Primary package is not outdated."
+    end)
+end
+
+---@async
+---@param receipt InstallReceipt<InstallReceiptPackageSource>
+---@param _install_dir string
+---@diagnostic disable-next-line: unused-local
+function M.get_installed_primary_package_version(receipt, _install_dir)
+    return spawn
+        .gem({ "list" })
+        :map_catching(function(result)
+            local gems = M.parse_gem_list_output(result.stdout)
+            return Optional.of_nilable(gems[receipt.primary_source.package])
+                :or_else_throw "Failed to find gem package version."
+        end)
+end
+
+return M
diff --git a/lua/mason-registry/index.lua b/lua/mason-registry/index.lua
index 469f92d..0f95727 100644
--- a/lua/mason-registry/index.lua
+++ b/lua/mason-registry/index.lua
@@ -182,6 +182,7 @@ return {
   ["slint-lsp"] = "mason-registry.slint-lsp",
   solang = "mason-registry.solang",
   solargraph = "mason-registry.solargraph",
+  ["solargraph-system"] = "mason-registry.solargraph-system",
   solhint = "mason-registry.solhint",
   solidity = "mason-registry.solidity",
   ["solidity-ls"] = "mason-registry.solidity-ls",
diff --git a/lua/mason-registry/solargraph-system/init.lua b/lua/mason-registry/solargraph-system/init.lua
new file mode 100644
index 0000000..7f6386b
--- /dev/null
+++ b/lua/mason-registry/solargraph-system/init.lua
@@ -0,0 +1,11 @@
+local Pkg = require "mason-core.package"
+local gem = require "mason-core.managers.system-gem"
+
+return Pkg.new {
+    name = "solargraph-system",
+    desc = [[Solargraph is a Ruby gem that provides intellisense features through the language server protocol. Installed via a system provided `gem` command.]],
+    homepage = "https://solargraph.org",
+    languages = { Pkg.Lang.Ruby },
+    categories = { Pkg.Cat.LSP },
+    install = gem.packages { "solargraph" },
+}
diff --git a/lua/mason/mappings/language.lua b/lua/mason/mappings/language.lua
index 4b9c8e0..0e40dd5 100644
--- a/lua/mason/mappings/language.lua
+++ b/lua/mason/mappings/language.lua
@@ -92,7 +92,7 @@ return {
   reason = { "reason-language-server" },
   rescript = { "rescript-lsp" },
   ["robot framework"] = { "robotframework-lsp" },
-  ruby = { "erb-lint", "rubocop", "ruby-lsp", "solargraph", "sorbet", "standardrb" },
+  ruby = { "erb-lint", "rubocop", "ruby-lsp", "solargraph", "solargraph-system", "sorbet", "standardrb" },
   rust = { "codelldb", "cpptools", "rust-analyzer" },
   salt = { "salt-lsp" },
   scss = { "css-lsp", "prettier", "prettierd" },
```

mason-lspconfig.nvim:
```diff
diff --git a/lua/mason-lspconfig/mappings/filetype.lua b/lua/mason-lspconfig/mappings/filetype.lua
index b80f8eb..88d2210 100644
--- a/lua/mason-lspconfig/mappings/filetype.lua
+++ b/lua/mason-lspconfig/mappings/filetype.lua
@@ -124,7 +124,7 @@ return {
   rnoweb = { "ltex" },
   robot = { "robotframework_ls" },
   rst = { "esbonio", "ltex" },
-  ruby = { "ruby_ls", "solargraph", "sorbet" },
+  ruby = { "ruby_ls", "solargraph", "sorbet", "solargraph-system" },
   rust = { "rust_analyzer" },
   sass = { "emmet_ls", "tailwindcss" },
   scss = { "cssls", "emmet_ls", "stylelint_lsp", "tailwindcss" },
@@ -166,4 +166,4 @@ return {
   ["yaml.docker-compose"] = { "yamlls" },
   zig = { "zls" },
   zir = { "zls" }
-}
\ No newline at end of file
+}
diff --git a/lua/mason-lspconfig/mappings/server.lua b/lua/mason-lspconfig/mappings/server.lua
index 6936aa1..9f49485 100644
--- a/lua/mason-lspconfig/mappings/server.lua
+++ b/lua/mason-lspconfig/mappings/server.lua
@@ -97,7 +97,7 @@ M.lspconfig_to_package = {
     ["serve_d"] = "serve-d",
     ["slint_lsp"] = "slint-lsp",
     ["solang"] = "solang",
-    ["solargraph"] = "solargraph",
+    ["solargraph"] = "solargraph-system",
     ["solc"] = "solidity",
     ["solidity"] = "solidity-ls",
     ["sorbet"] = "sorbet",
```

---------------------

The problem, however, is that resulting system-gem doesn't report version information. Also, with mason-lspconfig mapping servers to installs 1-1, I need to modify things further to allow for multiple versions of the same LSP installs.

But overall, resulting "solargraph-system" package works exactly how I need it to work when it comes to loading gems.

**Comment by MetuMortis-code** [comment]
![Screenshot_20221104_220143](https://user-images.githubusercontent.com/78408599/200055818-8c7a5f70-868d-4ac9-804d-3bab2218fef2.png)

I can't install any ruby lsp.
