### ISSUE TITLE
Grammarly config does nothing.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [williamboman/mason-lspconfig.nvim#358]
### Problem description

I have followed the configuration schema given by Mason to document dialect and domain:
```lua
for lsp, config in pairs({
  rust_analyzer = {
    ["rust-analyzer"] = {
      server = {
        path = "C:/Users/User/.cargo/bin/ra-multiplex.exe",
      },
    },
  },
  grammarly = {
    grammarly = {
      config = {
        ["documentDialect"] = "british",
        ["documentDomain"] = "academic",
      },
    },
  },
}) do
  config.on_attach = on_attach
  config.capabilities = capabilities
  lspconfig[lsp].setup(config)
end
```
Despite the language server started correctly, I still got diagnostics like
```
**Change the spelling**

The spelling of 
**colour**
 is a non-American variant. For consistency, consider replacing it with the American English spelling.


… my all-day 
<span style="color:#F00;">~~colour~~</span>
color …
```

I have also tried different config keys, such as `grammarly.documentDialect`, `config.documentDialect`, or just simply `documentDialect` but none of them works. After trying out other config entires, such as `grammarly.suggestionCategories.vocabulary`, it appears that neither do these entries work.

### Why do you think this is an issue with mason-lspconfig.nvim?

I do ponder whether this is the fault of Mason. But unfortunately, I am unable to test the functionalities on newer versions due to https://github.com/williamboman/mason.nvim/discussions/1624 and I ran into even more problems trying to build the latest https://github.com/znck/grammarly
```
PS C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver> node -v
v18.19.0
PS C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver> pnpm build

> @ build C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver
> rollup -c && node scripts/build-web-extension.mjs

[!] SyntaxError: Cannot use import statement outside a module
C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver\rollup.config.js:1
import typescript from '@rollup/plugin-typescript'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\loadConfigFile.js:618:17)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at loadConfigFromBundledFile (C:\Users\User\AppData\local\nvim-data\mason\packages\grammarly-languageserver\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\loadConfigFile.js:624:42)

 ELIFECYCLE  Command failed with exit code 1.
```

I feel like stuck in a maze now. I wish I could receive some clues of what should do next.

### Neovim version (>= 0.7)

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320

### Operating system/version

Windows 11 Home 21H2 22000.1936

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

grammarly-languageserver

### Steps to reproduce

1. Set NodeJS version to v16.20.0 (as this langauge server does not work on v18 or higher).
2. Install grammarly-languageserver 0.0.4 via Mason.
3. Apply the configuration above.
4. Open a Markdown file written in British English and wait for the diagnostics.

### Actual behavior

The diagnostics are British-wise.

### Expected behavior

The diagnostics are American-wise, other configs failed too. The default config is always applied.

### LspInfo

```Text
Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: C:\Users\User\AppData\Local\nvim-data\lsp.log
 Detected filetype:   markdown
 
 1 client(s) attached to this buffer: 
 
 Client: grammarly (id: 1, bufnr: [3])
 	filetypes:       markdown
 	autostart:       true
 	root directory:  C:/Users/User/AppData/Local/nvim
 	cmd:             C:\Users\User\AppData\Local\nvim-data\mason\bin\grammarly-languageserver.CMD --stdio
 
 Configured servers list: grammarly, lua_ls, clangd, rust_analyzer, gopls, intelephense, cssls, tsserver, html
```

### Healthcheck

```Text


==============================================================================
mason: 

- ERROR No healthcheck found for "mason" plugin.

```

**Comment by Endermanbugzjfc** [comment]
# Update update
I was wrong, the correct config should be:
```diff
  grammarly = {
+ settings = {
    grammarly = {
      config = {
        ["documentDialect"] = "british",
        ["documentDomain"] = "academic",
      },
+  },
    },
  },
})
```
*Notice that the rust-analyzer one is also incorrect.*
